name: BuildLiteLoaderPlugin

on:
  pull_request:
    types: [closed]

env:
  PluginName: CrowbarsLLBDSPlugins

jobs:
  build:
    if: github.event.pull_request.merged == true
    
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
            
    - name: Download latest Bedrock
      run: |
        Set-PSDebug -Trace 1;
        $content = Invoke-WebRequest -UseBasicParsing -uri "https://github.com/crowbarmaster/BedrockManagementService/raw/master/BMS_Files/bedrock_version_manifest.json";
        $jsonObj = $content | ConvertFrom-Json;
        $latestVer = $jsonObj | Select-Object -Last 1;
        $BDSUrl = "https://minecraft.azureedge.net/bin-win/bedrock-server-" + $latestVer.version + ".zip";
        Invoke-WebRequest -uri $BDSUrl -OutFile "BDS.zip";
        
    - name: Expand Bedrock
      run: |
        Expand-Archive "BDS.zip" -DestinationPath ".\BDS";

    - name: Deploy Libraries
      run: |
        $curDir = Get-Location;
        $bdsDir = $curDir.ToString() + "\BDS";
        $outDir = $curDir.ToString() + "\SDK\lib";
        .\SDK\tools\LibraryBuilder.exe -o $outDir.ToString() $bdsDir.ToString();
    
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Plugin
      run: |
        MSBuild.exe .\${{ env.PluginName }}.sln -property:Configuration=Release
    
    - name: Compress Files
      run: |
        Compress-Archive .\x64\Release\*.dll .\${{ env.PluginName }}.zip
        Compress-Archive .\x64\Release\*.pdb .\${{ env.PluginName }}PDB.zip
    
    - name: Set version string
      run: |
        $TMP = (get-item .\x64\Release\${{ env.PluginName }}.dll).VersionInfo.FileVersion;
        echo "PROJ_VER=$TMP" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append;
        echo "${{ env.PROJ_VER }}"
    
    - name: Push Automatic Release
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ env.PROJ_VER }}"
        prerelease: true
        title: "Development Build: Version ${{ env.PROJ_VER }}"
        files: |
            "${{ env.PluginName }}*.zip"